# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=50)),
                ('active', models.IntegerField(default=0)),
            ],
        ),
    ]
