# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=150)),
                ('price', models.IntegerField(default=0)),
            ],
        ),
    ]
